#! /usr/bin/env python3

import rospy
from visualization_msgs.msg import Marker

class waypoints():
    rospy.init_node('rviz_marker')

    marker_pub = rospy.Publisher("/visualization_marker", Marker, queue_size = 10)

    marker = Marker()
    marker.header.frame_id = "world"
    marker.header.stamp = rospy.Time.now()

    # set shape, Arrow: 0; Cube: 1 ; Sphere: 2 ; Cylinder: 3
    marker.type = 2

    # Set the scale of the marker
    marker.scale.x = 1.0
    marker.scale.y = 1.0
    marker.scale.z = 1.0

    # Set the color
    marker.color.r = 0.0
    marker.color.g = 1.0
    marker.color.b = 0.0
    marker.color.a = 1.0

    # Set the pose of the marker
    def markersList(self):
        for i in range(len(waypoints_)):
            self.marker.id = i
            self.marker.pose.position.x = waypoints_[i][0]
            self.marker.pose.position.y = waypoints_[i][1]
            self.marker.pose.position.z = 0
            self.marker.pose.orientation.x = 0.0
            self.marker.pose.orientation.y = 0.0
            self.marker.pose.orientation.z = 0.0
            self.marker.pose.orientation.w = 1.0
            self.marker_pub.publish(self.marker)
    rospy.rostime.wallsleep(1.0)

waypoints_ = rospy.get_param("waypoints")
while not rospy.is_shutdown():
  waypoints()