#! /usr/bin/env python3
import copy
import rospy
from visualization_msgs.msg import Marker, MarkerArray
import tf_conversions # Because of transformations
import tf2_ros
import geometry_msgs.msg
import nav_msgs.msg
import ros_sim.msg
rospy.init_node('rviz_marker_and_point_tf_publisher')
marker_pub = rospy.Publisher("/visualization_marker_array", MarkerArray, queue_size = 10)
marker = Marker()
marker.header.frame_id = "world"
marker_arr = MarkerArray()
marker_array = [[1,10],[9,2],[7,10],[2,2],[4,8]]
marker.header.stamp = rospy.Time.now()
# set shape, Arrow: 0; Cube: 1 ; Sphere: 2 ; Cylinder: 3
marker.type = 2
# Set the scale of the marker
marker.scale.x = 0.2
marker.scale.y = 0.2
marker.scale.z = 0.2
# Set the color
marker.color.r = 0.0
marker.color.g = 1.0
marker.color.b = 0.0
marker.color.a = 1.0
def place_markers():
    for i in range(len(marker_array)):
        temp_marker = copy.deepcopy(marker)
        # Set the pose of the marker
        temp_marker.id = i
        temp_marker.pose.position.x = marker_array[i][0]
        temp_marker.pose.position.y = marker_array[i][1]
        temp_marker.pose.position.z = 0.0
        temp_marker.pose.orientation.x = 0.0
        temp_marker.pose.orientation.y = 0.0
        temp_marker.pose.orientation.z = 0.0
        temp_marker.pose.orientation.w = 1.0
        marker_arr.markers.append(temp_marker)
while not rospy.is_shutdown():
    place_markers()
    marker_pub.publish(marker_arr)
    rospy.rostime.wallsleep(1.0)